### ISSUE TITLE
Script Responsibilities

### ISSUE THREAD

**Issue by EvanYathon** [UBC-MDS/DSCI_522_Capital_Bikeshare_Analysis#12]
For the second script

_Second script that reads the data from the first script and creates an exploratory visualization that is useful to help the reader/consumer understand that dataset. This should take two arguments:
a path/filename pointing to the data
a path/filename prefix where to write the figure to and what to call it (e.g., results/this_eda.png)_

I was thinking a few different plots such as categorical boxplots for our ridership ranges, or maybe we can utilize the `ggpairs` function.  I can work on this part of the pipeline and upload a preliminary script.

**Comment by Mikeymice** [comment]
that is great idea!!!

yes box plot and even jitter plot sounds great choices with the category, we can maybe use the `ggpairs` first to get an overview of possible correlation and later draw those good candidates for the deciding factors with `ggplot2`

**Comment by EvanYathon** [comment]
I can look into the fourth script then when you're done!
