### ISSUE TITLE
Changing the question

### ISSUE THREAD

**Issue by EvanYathon** [UBC-MDS/DSCI_522_Capital_Bikeshare_Analysis#6]
Hey Mike,
I'm just reading Tiffany's posted [issue](https://github.ubc.ca/MDS-2018-19/DSCI_522_dsci-workflows_students/issues/9) and thought we maybe we should change our question to find out 'what are the top predictors of ridership?'

In particular, maybe doing something similar to this:

_If you are interested in know the top N predictors from a decision tree (because that is the predictive question you are asking), in scikit-learn you can access a score for each feature through the `feature_importances_` field after fitting, and then grab the top 3._

The reason I'm wondering if we should change the question is that our current question doesn't seem to fit the criteria.  It currently seems too general to me.

What are your thoughts?

**Comment by Mikeymice** [comment]
I think it is a great idea to change the question. I would go with top 3 features. can i think we can draw the tree easily too

**Comment by EvanYathon** [comment]
Right on!  I will change the README and update our plan of attack.  I think it will stay mostly the same except for drawing the tree and/or calling `feature_importances`.

**Comment by EvanYathon** [comment]
Changed the README and submitted a pull request
